# This the default config from which all other configurations inherit
## For a more detailed example of the themes capabilities look at "development/config.toml"
languageCode = "de-de"
title = "Freifunk-Leipzig"
baseURL = "https://freifunk-leipzig.de"
theme = "hugo-html5up-alpha"
disqusShortname = ""

[menu]
  [[menu.map]]
    identifier = "Meshviewer"
    name = "Meshviewer"
    url = "map"
    weight = 10

  [[menu.firmware]]
    identifier = "Firmware"
    name = "Gluon"
    url = "gluon/"
    weight = 10
  
  [[menu.kontakt]]
    identifier = "Impressum"
    name = "Impressum"
    url = "https://freifunk.net/impressum/"
    weight = 10
  
  [[menu.kontakt]]
    identifier = "Datenschutz"
    name = "Datenschutz"
    url = "https://freifunk.net/datenschutz/"
    weight = 20

#[communtiy]
#  url_map_meshviewer = "http://karte.leipzig.freifunk.net:8018/meshviewer2/build/#!/de/map"

[params]
  description = "Another fine responsive site template freebie by HTML5 UP."
  images = ["images/pic01.jpg"]
  author = "Hugo Port: [Nelson/Roberto](https://nelsonroberto.com/)"
  copyright = "© Untitled. All rights reserved."
  design = "Design: [HTML5 UP](http://html5up.net/)"
  mainSections = ["blog"]

### Footer Social Media Links ###
[[params.share]]
title = "facebook"
icon = "fa-facebook-f" # fontawesome icons https://fontawesome.com/icons?d=gallery&s=brands
link = "https://de-de.facebook.com/FreifunkLeipzig"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "https://twitter.com/freifunk_l?lang=de"

[[params.share]]
title = "github"
icon = "fa-github"
link = "https://github.com/freifunk-leipzig"